# render.yaml (example, adjust paths as needed)
services:
  - type: web
    name: node-api
    env: node
    # ... (your existing Node.js configuration)

  - type: worker # Or 'web' if it's a Python API, or 'cronjob'
    name: python-script
    env: python
    # If astro-finding.py is in a subfolder like 'python/', use:
    # rootDirectory: ./python
    buildCommand: python3 -m pip install -r requirements.txt && npm install && npm run build
   # This line is crucial
    startCommand: python3 astro-finding.py # Or 'python' depending on Render's default alias
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.1 # Or whatever version you prefer